# .github/workflows/build-and-push.yml
name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # Führt den Job bei jedem Push auf den main-Branch aus

jobs:
  build:
    runs-on: ubuntu-latest # Der Job läuft auf einem von GitHub bereitgestellten Linux-Server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        # Dieser Befehl kompiliert, testet und baut die Anwendung
        run: ./mvnw package

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        # Dieser Quarkus-Befehl baut das Docker-Image und pusht es zu Docker Hub
        run: ./mvnw package -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.container-image.group=${{ secrets.DOCKER_USERNAME }}